name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run e2e tests in simulated X environment
        run: xvfb-run -a npm run test:e2e
        if: runner.os == 'Linux'

      - name: Run e2e tests
        if: runner.os != 'Linux'
        uses: nick-fields/retry@e88a9994b039653512d697de1bce46b00bfe11b5
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: npm run test:e2e

